# PORT
server:
  port: 8088

# SECURITY
security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expire-length: 180000 # 3 minutes

# SPRING SERVICE
spring:
  application:
    name: api-authentication
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_DATABASE_NAME}?useTimezone=true&serverTimezone=UTC
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
    hikari:
      auto-commit: true
      isolation-level: CONNECTION  # ou TRANSACTION_READ_COMMITTED
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
  # JPA, SQL
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
# EMAIL API INTEGRATIONS
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_EMAIL_GOOGLE}
    password: ${SECRET_EMAIL_GOOGLE}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# SMS API INTEGRATIONS
message:
  telesign:
    user:
      customerId: ${TELESIGN_CUSTOMER_ID}
      apiKey: ${TELESIGN_APIKEY}
    url:
      sms: ${TELESIGN_URL_SMS}
  gti:
    user: ${GTI_EMAIL}
    token: ${GTI_TOKEN}
    url: ${GTI_URL}

# LOGGER
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE